### ISSUE TITLE
Doesnt work in REACT app

### ISSUE THREAD

**Issue by Jhollman** [vision10/mssql-ssrs#17]
I tried to install this in my REACT app but i get this:
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

30 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.70.0 compiled with 30 errors and 24 warnings in 9318 ms
```

I tries installing the missing references:
`npm i fs assert https-browserify os os-browserify react-app-rewired stream-browserify stream-http path-browserify crypto-browserify
`
but got no luck and im too noob in this

**Comment by vision10** [comment]
You have some errors because this package was not really meant for frontend apps. 
I wrote it to work with node.js so as to not expose the reporting server link, 
Some refactoring is needed to work in frontend. 
I will take a look at this a bit later, probably some time next week

also this might help with your webpack configuration
https://stackoverflow.com/a/64802753

**Comment by BlueMystical** [comment]
Thanks! i appreciate the repply.
